name: Test Action

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Render Architecture Diagrams
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Render diagrams (JSON)
        uses: pleimann/structurizr@v1
        with:
          workspace: 'big-bank-plc.json'
          output-dir: 'docs/diagrams/json'
      
      - name: Render diagrams (DSL)
        uses: pleimann/structurizr@v1
        with:
          workspace: 'big-bank-plc.dsl'
          output-dir: 'docs/diagrams/dsl'